name: 'Terraform'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

#    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
#    - name: Host file test
#      run: echo -e "[myhost]\n10.0.0.1" >> inv
#      
#    - name: cat inv
#      run: pwd && cat inv

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_version: 1.0.9
    
    - name: Terraform Init
      id: init
      run: terraform init
      
    - name: Terraform plan
      id: plan
      run: terraform plan
      
    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve
      
    - name: Check stdout
      run: echo ${{ steps.plan.outputs.stdout }} >> inv
      
    - name: list content
      run: ls -la

    - name: upload inv
      uses: actions/upload-artifact@v2
      with:
          name: inv
          path: inv

  ansible:
    name: 'Ansible'
    runs-on: ubuntu-latest
    environment: production
    needs: [terraform]
    
    defaults:
      run:
        shell: bash
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
          name: inv
          
    - name: cat inv
      run: pwd && cat inv
