name: 'Terraform'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: echo -e "[myhost]\n10.0.0.1" >> inv
      
    - name: cat inv
      run: pwd && cat inv
    
    - name: upload inv
      uses: actions/upload-artifact@v2
      with:
          name: inv
          path: inv

  ansible:
    name: 'Ansible'
    runs-on: ubuntu-latest
    environment: production
    
    defaults:
      run:
        shell: bash
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
          name: inv
          
    - name: cat inv
      run: pwd && cat inv
      
    - name: Run ping against the host
      uses: actions/ansible-cli-action@master
      with:
          command: "ansible -i inv myhost -m ping"
