name: 'Terraform'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Nodejs
      uses: actions/setup-node@v2
      with:
         node-version: '14'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_version: 1.0.9
          terraform_wrapper: false
    
    - name: Terraform Init
      id: init
      run: terraform init
      
    - name: Terraform plan
      id: plan
      run: terraform plan
      
    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve
      
    - name: Parse test.json
      run: node parse_json.js

    - name: get state
      id: statepull
      run: terraform state pull > state.json
      
#     - name: filter json
#       run: echo ${{ steps.statepull.outputs.terraform-state }} | tee test.json #grep -vE "/home|^$|^:" state.json > test.json
      
    - name: cat state.json
      run: cat state.json

    - name: upload json
      uses: actions/upload-artifact@v2
      with:
          name: state.json
          path: state.json
#     - name: Setup Nodejs
#       uses: actions/setup-node@v2
#       with:
#           node-version: '14'
          
#     - name: Parse test.json
#       run: node parse_json.js > inv.ini

#     - name: upload test.json
#       uses: actions/upload-artifact@v2
#       with:
#           name: inv.ini
#           path: inv.ini

#   ansible:
#     name: 'Ansible'
#     runs-on: ubuntu-latest
#     environment: production
#     needs: [terraform]
    
#     defaults:
#       run:
#         shell: bash
    
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v2
    
#     - name: Download artifact
#       uses: actions/download-artifact@v2
#       with:
#           name: inv.ini
          
#     - name: cat inv.ini
#       run: cat -vte inv.ini
      
