name: 'Terraform'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Nodejs
      uses: actions/setup-node@v2
      with:
         node-version: '14'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_version: 1.0.9
          terraform_wrapper: false
    
    - name: Terraform Init
      id: init
      run: terraform init
      
    - name: Terraform plan
      id: plan
      run: terraform plan
      
    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve

    - name: get state
      id: statepull
      run: terraform state pull | tee state.json

    # - name: upload json
    #   uses: actions/upload-artifact@v2
    #   with:
    #       name: state.json
    #       path: state.json
    
    # - name: Download artifact
    #   uses: actions/download-artifact@v2
    #   with:
    #       name: state.json
    
    - name: parse json
      run: node parse_json.js state.json > state2.json

    - name: upload json
      uses: actions/upload-artifact@v2
      with:
          name: state2.json
          path: state2.json

#   ansible:
#     name: 'Ansible'
#     runs-on: ubuntu-latest
#     environment: production
#     needs: [terraform]
    
#     defaults:
#       run:
#         shell: bash
    
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v2
    
#     - name: Download artifact
#       uses: actions/download-artifact@v2
#       with:
#           name: inv.ini
          
#     - name: cat inv.ini
#       run: cat -vte inv.ini
      
